### PR TITLE
added test for assembled adt constructors

### PR DESCRIPTION
**Pull request by rdaly525**
Here is an example of using a Tuple constructor from within __call__ 

Jackson, let me know if this is sufficient your needs.

Caleb let me know if you see anything unsafe about this. Ill try to clean up the API before trying to merge

### CODE REVIEW

**Comment by cdonovick** [comment]
Maybe hold off on this preparing my magma adt pr right now and we going to be touching a lot of the same files

**Comment by jack-melchert** [comment]
Hey Ross, can we revisit this? It no longer works after Caleb's changes to the magma adt files.

**Comment by rdaly525** [comment]
@jack-melchert Sure, Ill take another look

**Comment by rdaly525** [comment]
Closing due to #152

**Pull request closed without merging**
