### PR TITLE
Move utility function to utils file

### PR DESCRIPTION
**Pull request by leonardt**
This rewriter is used in lassen to replace enums with their concrete, assembled BitVector values (for magma), for now I move this to a utils file so it can be used by the new assembler without incurring the deprecation warning.

### CODE REVIEW

**Comment by leonardt** [comment]
Once we've migrated magma to use the hwtypes ADTs I think we'll be able to drop this or move this code to magma internals.

**Comment by leonardt** [comment]
Needs to merged with https://github.com/StanfordAHA/lassen/pull/150 for garnetflow to work.

**Comment by rdaly525** [comment]
Not sure why garnet flow is still reporting broken. Lassen master is passing with the warnings + auto-assembler fixed.

**Comment by leonardt** [comment]
It looks like garnetflow is using a branch https://github.com/StanfordAHA/GarnetFlow/blob/master/scripts/install.sh#L25 that may not have the latest changes from https://github.com/StanfordAHA/garnet/pull/357

**Comment by cdonovick** [comment]
@leonardt Do you think we can merge this?

**Comment by rdaly525** [comment]
These need to get merged first.

https://github.com/StanfordAHA/garnet/pull/359
https://github.com/StanfordAHA/garnet/pull/359

Also in general this flow is pretty tedious and complicated. I am open to other suggestions.

**Pull request merged**
