### PR TITLE
Master family

### PR DESCRIPTION
**Pull request by rdaly525**
This is an attempt to simplify writing peak classes to not require the need for a family closure.
This PR does the following:
-Defines a peak metaclass that captures the locals and globals (using code similar to magma.circuit.sequential) in an attribute called _env_
-Defines a rebind(family) function that returns a new class where all references to types derived from family (ADT types, BitVector, Bit) are transformed to the appropriate version from the passed in family

Limitations:
-Defining multiple classes with the same name in the same file causes problems due to inspect.getsource() getting incorrect code.

### CODE REVIEW

**Comment by cdonovick** [comment]
Needs to pass garnet flow

**Comment by rdaly525** [comment]
@rsetaluri, @leonardt, this is the PR that I mentioned earlier.

**Comment by rdaly525** [comment]
Depends on https://github.com/phanrahan/magma/pull/482
Will also need to be merged with lassen as well which I am currently working on.

@phanrahan + @cdonovick could you start reviewing this? Major changes were getting magma compilation working. Unfortunately this requires temporarily two versions of gen_register to exist. 

Another annoying issue was that in order to cache rebound Peak classes, I needed extra information to distinguish peak classes that were generated using different arguments to a function. I chose a slightly hacky way by implementing a "uniquify" method. Perhaps you can recommend a better way.

**Comment by phanrahan** [comment]
I looked over the user-level code. Much nicer.

Need to spend more time on the metaclass part.

**Comment by cdonovick** [comment]
For how to do class caching see: https://github.com/leonardt/hwtypes/blob/master/hwtypes/adt_meta.py#L118

Recall the arguments to `metaclass.__new__` are:
`name: str` the name of the class being created
`bases: Tuple[type]`  the bases of the of the class being created.
`namespace: dict[str, ...]` the dict containing all the methods / class variables declared in the class being created. 
`kwargs: dict[str, ...]` all the keyword arguments in the the class declaration excluding metaclass

For example
```Python
class Foo(Bar, foobar=1, metaclass=meta): 
   baz = 2
```
will call:
```Python
meta.__new__('Foo', (Bar,), {'baz': 2}, foobar=1)
```

So to properly cache a class you generally want to create an index into the cache which is `(name, bases, namespace, kwargs)`. Now `namespace` and `kwargs` are not hashable types so either `frozenset(<dict>.items())` or `tuple(<dict>.items())` can be used for order independent and order dependent keys respectively.

**Comment by rdaly525** [comment]
@cdonovick Could you give me an example of how to cache the following using a metaclass on Peak? I think adt is more constrained since you cannot define methods in the class.

If I go the route of caching using 'namespaces', I need to be able to cache the __call__ function. I have access to Foo's source code using inspect, but the source code still has a 'T' in it which I cannot differentiate.

```
def gen_foo(T):
  class Foo(Peak):
    def __call__(self, a : T): -> T
      return ~a
  return Foo

assert gen_foo(Bit) is gen_foo(Bit)
assert gen_foo(Bit) is not gen_foo(SMTBit)
```

**Comment by cdonovick** [comment]
I think there is a number of ways we could approach this.  I think perhaps the easiest would be to pass to T the class during construction, e.g.:

```Python
def gen_foo(T):
    class Foo(Peak, T=T):
        def __call__(self, a: T) -> T:
            return ~a
    return Foo
```

Another way would be to create some `PeakGenerator` base class so that instead of defining a closure we define a Generator which could handle caching:

```
class PeakGenerator:
    @abstractmethod
    def generate(self, *args, **kwargs): pass

    def __call__(self, *args, **kwargs):
class GenFoo(PeakGenerator):
    def generate(

**Comment by rdaly525** [comment]
Rebinding hit major issues, so closing this for now

**Pull request closed without merging**
