### PR TITLE
Magma adt final

### PR DESCRIPTION
**Pull request by cdonovick**

### CODE REVIEW

**Comment by cdonovick** [comment]
Oops test failing because hwtypes needs a new release.  Will fix

**Comment by rdaly525** [comment]
@jack-melchert, take a look at these changes. It should simplify your generators. Basically you now do not have to use the Tuple_fc, Enum_fc, etc... nor do you have to wrap any instruction ADT type in a family closure

**Comment by cdonovick** [comment]
@rdaly525  Don't you need the instruction type to have SMTBitVector fields in a SMT context? (so still need to wrap adt types with data fields?)

**Comment by jack-melchert** [comment]
This looks great, it will significantly cleanup a lot of my code. Thanks!

**Comment by rdaly525** [comment]
@cdonovick @jack-melchert sorry, yes I mispoke. You still need a family closure if any fields of your ADT type is a Bit or BitVector.

**Pull request merged**
