### PR TITLE
Use Sequential2 [DO NOT MERGE UNTIL AFTER TAPEOUT]

### PR DESCRIPTION
**Pull request by cdonovick**

### CODE REVIEW

**Comment by cdonovick** [comment]
This PR should finally be done.

**Review by rdaly525 — APPROVED** [review]
Looks good and like what we talked about

**Comment by rdaly525** [comment]
@jack-melchert I highly suspect this will break your DSE peak generation code. But hopefully will make it easier.

**Comment by cdonovick** [comment]
https://github.com/StanfordAHA/aha/pull/1079

**Pull request merged**
